### ISSUE TITLE
Export `getMagicToken`

### ISSUE THREAD

**Issue by lorensr** [arunoda/use-magic-link#1]
For those who don't want to use the provided `fetch`

👋 Hi Arunoda 😄

**Comment by arunoda** [comment]
@lorensr hey hey :D 

I think you can use the original `magic` API instance: https://github.com/arunoda/use-magic-link#authmagic

**Comment by arunoda** [comment]
API is pretty simple: https://github.com/arunoda/use-magic-link/blob/master/src/use-magic-link.js#L28

**Comment by lorensr** [comment]
I see, sounds good, thanks! 🤗
